---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "webfrontend-config"
  labels:
    app.kubernetes.io/name: "aspiretest-apphost"
    app.kubernetes.io/component: "webfrontend"
    app.kubernetes.io/instance: "{{.Release.Name}}"
data:
  ASPNETCORE_URLS: "http://+:8081" #;https://+:8082
  OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "{{ .Values.config.webfrontend.OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES }}"
  OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "{{ .Values.config.webfrontend.OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES }}"
  OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "{{ .Values.config.webfrontend.OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY }}"
  ASPNETCORE_FORWARDEDHEADERS_ENABLED: "{{ .Values.config.webfrontend.ASPNETCORE_FORWARDEDHEADERS_ENABLED }}"
  #HTTP_PORTS: {{ .Values.config.webfrontend.HTTP_PORTS }}
  CACHE_HOST: "{{ .Values.config.webfrontend.CACHE_HOST }}"
  CACHE_PORT: "{{ .Values.config.webfrontend.CACHE_PORT }}"
  APISERVICE_HTTP: "{{ .Values.config.webfrontend.APISERVICE_HTTP }}"
  services__apiservice__http__0: "{{ .Values.config.webfrontend.services__apiservice__http__0 }}"
  APISERVICE_HTTPS: "{{ .Values.config.webfrontend.APISERVICE_HTTPS }}"
  services__apiservice__https__0: "{{ .Values.config.webfrontend.services__apiservice__https__0 }}"
